spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo-test?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    database: 2
    timeout: 10000
    host: 127.0.0.1
    port: 6379
    password: 123456
  jpa:
    generate-ddl: false

erupt:
  uploadPath: /opt/erupt/pictures

